server:
  port: 9090

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      show-sql: true
    properties:
     hibernate:
      show-sql: true
      format_sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/arcomage
    username: arcomage
    password: arcomage
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8

logging:
  loggingXml: false